apiVersion: v1
kind: Service
metadata:
  name: dbcontainer
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage1
        persistentVolumeClaim:
          claimName: mysql-pv-claim1
      containers:
      - image: mysql:5.6
        name: dbcontainer
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: Vamsee2k20
        - name: MYSQL_DATABASE
          value: pythondb
        ports:
        - name: tcp
          containerPort: 3306
        volumeMounts:
        - name: mysql-storage1
          mountPath: /var/lib/mysql
